### ISSUE TITLE
JPASQLQuery: Can not set java.time.LocalDateTime field to java.sql.Timestamp

### ISSUE THREAD

**Issue by Oodachi** [OpenFeign/querydsl#155] opened 2023-12-10 08:42 UTC

**Comment by Oodachi** [comment] 2023-12-10 08:43
#https://github.com/querydsl/querydsl/issues/2382

**Comment by velo** [comment] 2023-12-10 18:54
@Oodachi could you give me an example (preferable a limited scope junit test) demonstrating the issue?

**Comment by danielvion** [comment] 2023-12-11 08:04
I think this is because querydsl is still using the `joda.time` instead of `java.time` API.

**Comment by velo** [comment] 2023-12-13 20:50
New release out with plenty of fixed on `java.time` territory, give it a shot

https://github.com/OpenFeign/querydsl/releases/tag/6.0.0.M2

**Comment by Oodachi** [comment] 2023-12-20 08:14
QClass cannot be generated after upgrading to 6.0.0.M2
https://github.com/Oodachi/oodachi-querydsl-example

**Comment by velo** [comment] 2023-12-20 18:16
IIRC, when lombok is add to the mix you need to declare the `annotationProcessors` too:

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessors>
                        <annotationProcessor>lombok.launch.AnnotationProcessorHider$AnnotationProcessor</annotationProcessor>
                        <annotationProcessor>com.querydsl.apt.jpa.JPAAnnotationProcessor</annotationProcessor>
                    </annotationProcessors>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>io.github.openfeign.querydsl</groupId>
                            <artifactId>querydsl-apt</artifactId>
                            <version>6.0.0.M2</version>
                         </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
```

Did that on you example and the QPost was generated.

**Comment by velo** [comment] 2023-12-20 18:19
I dropped the version to 5.1.1 and saw same behaviour:

```
velo@DESKTOP-8FS1K0S:~/oodachi-querydsl-example$ git diff
diff --git a/pom.xml b/pom.xml
index 90e33ba..50a4ac4 100644
--- a/pom.xml
+++ b/pom.xml
@@ -28,17 +28,19 @@
         <dependency>
             <groupId>io.github.openfeign.querydsl</groupId>
             <artifactId>querydsl-jpa</artifactId>
-            <version>6.0.0.M2</version>
+            <version>5.1.1</version>
+            <classifier>jakarta</classifier>
         </dependency>
         <dependency>
             <groupId>io.github.openfeign.querydsl</groupId>
             <artifactId>querydsl-sql</artifactId>
-            <version>6.0.0.M2</version>
+            <version>5.1.1</version>
         </dependency>
         <dependency>
             <groupId>io.github.openfeign.querydsl</groupId>
             <artifactId>querydsl-apt</artifactId>
-            <version>6.0.0.M2</version>
+            <version>5.1.1</version>
+            <classifier>jakarta</classifier>
         </dependency>
         <dependency>
             <groupId>org.postgresql</groupId>
@@ -89,7 +91,7 @@
                         <path>
                             <groupId>io.github.openfeign.querydsl</groupId>
                             <artifactId>querydsl-apt</artifactId>
-                            <version>6.0.0.M2</version>
+                            <version>5.1.1</version>
                          </path>
                     </annotationProcessorPaths>
                 </configuration>
velo@DESKTOP-8FS1K0S:~/oodachi-querydsl-example$ ls target/generated-sources/annotations/
velo@DESKTOP-8FS1K0S:~/oodachi-querydsl-example$
```

Can you get me a 5.1.1 (or even an original querydsl 5.0 example) where this works as expected?

**Comment by Oodachi** [comment] 2023-12-21 08:06
> Can you get me a 5.1.1 (or even an original querydsl 5.0 example) where this works as expected?

https://github.com/Oodachi/oodachi-querydsl-example/blob/ac315ce206972c482fe8b18ca1d83eccb4bbe7a7/pom.xml#L93

I can't tell how to use it correctly. 😂

**Comment by Oodachi** [comment] 2023-12-22 01:51
> @Oodachi could you give me an example (preferable a limited scope junit test) demonstrating the issue?

https://github.com/Oodachi/oodachi-querydsl-example 

```java
@Test
void testJPASQLQuery() {
    JPASQLQuery<?> jpasqlQuery = new JPASQLQuery<>(entityManager, PostgreSQLTemplates.DEFAULT);

    List<PostVO> fetch = jpasqlQuery.select(Projections.fields(PostVO.class,
                    QPost.post.title,
                    QPost.post.content,
//                        QPost.post.date,
                    QPost.post.timestamp))
            .from(QPost.post).fetch();
    assertEquals(10, fetch.size());
}
```

error log

```
java.lang.IllegalArgumentException: Can not set java.time.LocalDateTime field io.github.oodachi.querydsl.PostVO.timestamp to java.sql.Timestamp

	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.base/java.lang.reflect.Field.set(Field.java:799)
	at com.querydsl.core.types.QBean.newInstance(QBean.java:226)
	at com.querydsl.jpa.FactoryExpressionTransformer.transformTuple(FactoryExpressionTransformer.java:48)
	at org.hibernate.sql.results.internal.RowTransformerTupleTransformerAdapter.transformRow(RowTransformerTupleTransformerAdapter.java:30)
	at org.hibernate.sql.results.internal.StandardRowReader.readRow(StandardRowReader.java:98)
	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:201)
	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:361)
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:168)
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:93)
	at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31)
	at org.hibernate.query.sql.internal.NativeSelectQueryPlanImpl.performList(NativeSelectQueryPlanImpl.java:97)
	at org.hibernate.query.sql.internal.NativeQueryImpl.doList(NativeQueryImpl.java:623)
	at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:427)
	at org.hibernate.query.Query.getResultList(Query.java:120)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:405)
	at jdk.proxy2/jdk.proxy2.$Proxy148.getResultList(Unknown Source)
	at com.querydsl.jpa.sql.AbstractJPASQLQuery.getResultList(AbstractJPASQLQuery.java:203)
	at com.querydsl.jpa.sql.AbstractJPASQLQuery.fetch(AbstractJPASQLQuery.java:235)
	at io.github.oodachi.querydsl.QuerydslApplicationTest.testJPASQLQuery(QuerydslApplicationTest.java:81)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by Oodachi** [comment] 2023-12-28 03:21
@velo Can I reopen this issue?

**Comment by velo** [comment] 2024-01-14 19:04
Ok, back from vacation, I finally had the time to investigate this.

The problem is the native query bit.

When you run a native query, you "loose" the jpa types, and for that reason date is read as java.sql.Date and timestamp as java.sql.Timestamp.

A way to make the issue extremely obvious, would be by generating `SPost` class from the database:

```
public class SPost extends com.querydsl.sql.RelationalPathBase<SPost> {

    private static final long serialVersionUID = 1493541160;

    public static final SPost post = new SPost("post");

    public final StringPath content = createString("content");

    public final DatePath<java.sql.Date> date = createDate("date", java.sql.Date.class);

    public final NumberPath<Long> id = createNumber("id", Long.class);

    public final DateTimePath<java.sql.Timestamp> timestamp = createDateTime("timestamp", java.sql.Timestamp.class);

    public final StringPath title = createString("title");

    public final com.querydsl.sql.PrimaryKey<SPost> postPkey = createPrimaryKey(id);

    public SPost(String variable) {
        super(SPost.class, forVariable(variable), "public", "post");
        addMetadata();
    }

    public SPost(String variable, String schema, String table) {
        super(SPost.class, forVariable(variable), schema, table);
        addMetadata();
    }

    public SPost(String variable, String schema) {
        super(SPost.class, forVariable(variable), schema, "post");
        addMetadata();
    }

    public SPost(Path<? extends SPost> path) {
        super(path.getType(), path.getMetadata(), "public", "post");
        addMetadata();
    }

    public SPost(PathMetadata metadata) {
        super(SPost.class, metadata, "public", "post");
        addMetadata();
    }

    public void addMetadata() {
        addMetadata(content, ColumnMetadata.named("content").withIndex(3).ofType(Types.VARCHAR).withSize(255).notNull());
        addMetadata(date, ColumnMetadata.named("date").withIndex(4).ofType(Types.DATE).withSize(13).notNull());
        addMetadata(id, ColumnMetadata.named("id").withIndex(1).ofType(Types.BIGINT).withSize(19).notNull());
        addMetadata(timestamp, ColumnMetadata.named("timestamp").withIndex(5).ofType(Types.TIMESTAMP).withSize(29).withDigits(6).notNull());
        addMetadata(title, ColumnMetadata.named("title").withIndex(2).ofType(Types.VARCHAR).withSize(255).notNull());
    }

}
```


If you try to read date from that one, is quite clear the types are not `java.time`.

I see a few ways of fixing it:
1 - require that `JPASQLQuery#from` be "sql" types like the `SPost` above, blocking "jpa"/`QPost`.
2 - introduce a conversion scheme that would let native types to specific java types (that is how spring handles this, but as big and complex spring is, some conversion do fall through the cracks)
3 - add `toLocalDate` to temporal fields to do a final conversion.

"3" seems a bit odd, as it would be `LocalDate.toLocalDate`, so, that would not give any compile time check just to handle a runtime problem.

I'm leaning towards "1".  That would be the most compile time check way of preventing the issue in the first place.

This are the changes I made to track the problem:
[patch.txt](https://github.com/OpenFeign/querydsl/files/13932764/patch.txt)


A work around for this would be using native query (SPost + QueryProjection that converts java.sql to java.time):

```
    @QueryProjection
    public PostVO(String title, String content, Date date, Timestamp timestamp) {
               this(title, content, date == null ? null: date.toLocalDate(),timestamp == null ? null: timestamp.toLocalDateTime());
       }
```

I still think "1" must be done.

**Comment by velo** [comment] 2024-01-14 19:38
https://github.com/OpenFeign/querydsl/pull/251

**Comment by Oodachi** [comment] 2024-01-15 06:42
AbstractJPAQuery has deprecated fetchResults so I chose to use AbstractJPASQLQuery.fetchResults to complete the paginated query.
I use JPAQuery to help JPA complete some complex queries, and JPASQLQuery to execute native SQL.

**Comment by Oodachi** [comment] 2024-01-15 10:41
I think JPASQLQuery should support QClass because it is not SQLQuery, QClass comes from Entity not database

**Comment by velo** [comment] 2024-01-15 18:11
But it is SQL. Otherwise, what is the difference from JPAQuery?

**Comment by Oodachi** [comment] 2024-01-16 01:03
> But it is SQL. Otherwise, what is the difference from JPAQuery?

https://github.com/OpenFeign/querydsl/blob/cdcf44ac650c6ab459ea803bfc3c769a887c566c/querydsl-jpa/src/main/java/com/querydsl/jpa/sql/JPASQLQuery.java#L24-L31

**Comment by velo** [comment] 2024-01-16 01:12
Eggxactly, run native SQL.

Problem is that right now it let you use non-native sql artifacts and it does a partial conversion behind the scenes....

bottom line is, wanna run JPA? Use JPAQuery and QClasses... 
want to run SQL? Use JPASQLQuery and SClasses.
Want odd errors? Mix them =)

Bottom line is what you want to do is not going to work, cause the native query want to return java.sql.Date

**Comment by Oodachi** [comment] 2024-01-16 01:24
> Eggxactly, run native SQL.
> 
> Problem is that right now it let you use non-native sql artifacts and it does a partial conversion behind the scenes....
> 
> bottom line is, wanna run JPA? Use JPAQuery and QClasses... want to run SQL? Use JPASQLQuery and SClasses. Want odd errors? Mix them =)
> 
> Bottom line is what you want to do is not going to work, cause the native query want to return java.sql.Date

you are right. I'm sorry I didn't read the documentation carefully.

http://querydsl.com/static/querydsl/latest/reference/html/ch02.html#d0e446

**Comment by velo** [comment] 2024-01-16 21:12
Fixed https://github.com/OpenFeign/querydsl/pull/251

**Closed by velo** 2024-01-16 21:12 UTC
